### ISSUE TITLE
Show paper's abstract when hovering over it with mouse

### ISSUE THREAD

**Issue by NullHypothesis** [NullHypothesis/censorbib#1]
When you move your mouse over a paper, I'd like the paper's abstract to pop up, to make it easy to get an idea of what the paper is about without having to open the pdf. This will require changing CensorBib's HTML/CSS (easy) and extracting all abstracts from the pdfs (a bit more tricky).

**Comment by tec1987** [comment]
https://github.com/mozilla/pdf.js
This maybe helpful

**Comment by NullHypothesis** [comment]
No longer interested in this.
